export const metadata = {
  title: "Disclaimer | FireThis",
  description: "Important disclaimers about FireThis's AI-generated feedback.",
};

export default function DisclaimerPage() {
  return (
    <div className="mx-auto max-w-3xl space-y-8 py-12 text-zinc-300">
      <div>
        <h1 className="text-4xl font-extrabold text-white">Disclaimer</h1>
        <p className="mt-2 text-sm text-zinc-500">Last updated: August 2026</p>
      </div>

      <p>
        FireThis provides AI-generated resume feedback and related tools for informational and
        educational purposes only. Please read the following carefully.
      </p>

      <Section title="1. Not Professional Advice">
        <p>
          FireThis is not a career counselor, recruiter, lawyer, accountant, or immigration
          advisor. Nothing on the Service constitutes professional career, legal, financial,
          tax, or immigration advice, and no professional relationship is created by using it.
        </p>
      </Section>

      <Section title="2. F-1 / OPT and Visa Content">
        <p>
          Any content relating to F-1, OPT, CPT, H-1B, visa sponsorship, or work authorization
          is <span className="font-semibold text-white">general information only and is not legal or
          immigration advice.</span> Immigration rules are complex, change frequently, and depend
          on your individual circumstances. FireThis does not guarantee sponsorship, work
          authorization, or any immigration outcome. Always consult a licensed immigration
          attorney or your school&rsquo;s Designated School Official (DSO) before making decisions.
        </p>
      </Section>

      <Section title="3. AI Can Be Wrong">
        <p>
          Our feedback is generated by AI, which can produce inaccurate, incomplete, or
          misleading information. Always review, verify, and use your own judgment before relying
          on or submitting anything generated by the Service.
        </p>
      </Section>

      <Section title="4. No Guarantee of Results">
        <p>
          Using FireThis does not guarantee interviews, job offers, or any particular outcome.
          Hiring decisions depend on many factors outside our control. Any scores, comparisons,
          or estimates (including &ldquo;Cooked Score&rdquo; and ATS match figures) are approximations, not
          guarantees.
        </p>
      </Section>

      <Section title="5. Your Responsibility">
        <p>
          You are responsible for the accuracy of the information in your resume and for your own
          career and application decisions. Never submit content you know to be false or
          misleading to an employer.
        </p>
      </Section>

      <Section title="6. Contact">
        <p>
          Questions? Contact us at{" "}
          <a href="mailto:cookiej180@gmail.com" className="text-brand-400 hover:underline">
            cookiej180@gmail.com
          </a>
          .
        </p>
      </Section>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="space-y-2">
      <h2 className="text-xl font-bold text-white">{title}</h2>
      <div className="space-y-2 text-zinc-300">{children}</div>
    </section>
  );
}
